name: Create and publish container image

on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:
  schedule:
    - cron: '10 17 * * 2'  # Every Tuesday of the month at 9:10 am PDT

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cas-php-client
  BASE_IMAGE_DOCKERFILE: ./Dockerfile

jobs:

  check:
    runs-on: ubuntu-latest

    outputs:
      differs: ${{ steps.check.outputs.differs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set base image
        run: |
          echo "BASE_IMAGE=$(grep 'FROM' ${{ env.BASE_IMAGE_DOCKERFILE}} | awk '{print $2}')" >> "$GITHUB_ENV"

      - name: Debug
        run: |
          echo ${{ env.BASE_IMAGE }}

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Check if update available
        id: check
        uses: ClementTsang/docker-check-base-image-diff@d8cf79d3bcda38fab44bc8c9afa60c4b3dee23de
        with:
          base-image: docker://${{ env.BASE_IMAGE }}
          derived-image: docker://${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}

  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # When invoked by schedule, only build if the base image is out of date
    if: ${{ needs.check.outputs.differs == 'true' ||  github.event_name != 'schedule' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for container
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags:
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: Build and push container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
